ALTER TABLE CUSTOMERS MODIFY SALARY DECIMAL(18,2) NOT NULL;

ALTER TABLE CUSTOMERS MODIFY SALARY DECIMAL(18,2) DEFAULT 5000.00;

ALTER TABLE CUSTOMERS ALTER COLUMN DROP DEFAULT

ALTER TABLE CUSTOMERS MODIFY AGE INT NOT NULL UNIQUE;

ALTER TABLE CUSTOMERS ADD CONSTRAINT myUniqueConstraint UNIQUE(AGE, SALARY);

ALTER TABLE CUSTOMERS DROP CONSTRAINT myUniqueConstraint;

ALTER TABLE CUSTOMERS DROP INDEX myUniqueConstraint;

ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID);

ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTID PRIMARY KEY (ID,NAME);

ALTER TABLE CUSTOMERS DROP PRIMARY KEY;

ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);

ALTER TABLE ORDERS DROP FOREIGN KEY;

ALTER TABLE CUSTOMERS MODIFY AGE INT NOT NULL CHECK (AGE >= 18);

ALTER TABLE CUSTOMERS ADD CONSTRAINT myCheckConstraint CHECK (AGE >= 18);

ALTER TABLE DROP CONSTRAINT myCheckConstraint;


