SELECT column1,column2,column2,column4 FROM table_name WHERE CONDITION

SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000;

SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE NAME = 'Hardik'

-- AND Operator
SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE NAME = 'Hardik' AND SALARY > 2000;

-- OR Operator
SELECT ID, NAME SALARY FROM CUSTOMERS WHERE SALARY > 2000 OR AGE > 18;

-- SQL LIKE Clause (%), (_)
SELECT * FROM table_name WHERE column1 LIKE 'XXX%';
SELECT * FROM table_name WHERE column1 LIKE '%XX%';
SELECT * FROM table_name WHERE column1 LIKE '_XXX';
SELECT * FROM table_name WHERE column1 LIKE '_XXXX_';

-- SQL TOP/LIMIT Clause
SELECT TOP number/percentage * FROM table_name WHERE CONDITION;
SELECT TOP 3 * FROM CUSTOMERS;
SELECT * FROM CUSTOMERS LIMIT 3;

-- SQL ORDER BY Clause
SELECT * FROM CUSTOMERS WHERE CONDITION ORDER BY NAME ASC, SALARY DESC;

-- SQL Group By
SELECT NAME, SUM(SALARY) FROM CUSTOMERS GROUP BY NAME;

-- SQL Distinct Keyword
SELECT DISTINCT SALARY FROM CUSTOMERS ORDER BY SALARY;

-- SQL NULL
SELECT column1, cloumn2, column3 FROM CUSTOMERS WHERE SALARY IS NOT NULL;
SELECT column1, cloumn2, column3 FROM CUSTOMERS WHERE SALARY IS NULL;

-- SQL HAVING CLAUSE
SELECT column1, column2 FROM table1, table2
WHERE [ conditions ]
GROUP BY column1, column2
HAVING [ conditions ]
ORDER BY column1, column2