CREATE TABLE CUSTOMERS(
    ID INT NOT NULL,
    NAME VARCHAR (20) NOT NULL,
    AGE INT NOT NULL UNIQUE,
    ADDRESS CHAR(50),
    SALARY DECIMAL(18,2) DEFAULT 5000.00,
    PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMERS(
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE NOT NULL INT,
    ADDRESS CHAR(25),
    SALARY CHAR(18,2),
    PRIMARY KEY (ID,NAME)
);

CREATE TABLE ORDER (
    ID INT NOT NULL,
    DATE DATETIME,
    CUSTOMER_ID INT REFERENCES CUSTOMERS(ID),
    AMOUNT DOUBLE,
    PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMERS(
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE NOT NULL INT CHECK (AGE>=18),
    ADDRESS CHAR(50),
    SALARY CHAR(18,2),
    PRIMARY KEY(ID)
);

-- Create Table Using another Table
CREATE TABLE NEW_TABLE_NAME AS SELECT [column1, column2, column3] FROM EXISTING_TABLE_NAME WHERE [Condition];

CREATE TABLE SALARY AS SELECT ID, SALARY FROM CUSTOMERS;

