SELECT * FROM CUSTOMERS
WHERE ID IN (SELECT ID 
            FROM CUSTOMERS
            WHERE SALARY > 4500);

INSERT INTO CUSTOMERS_BKP
SELECT * FROM CUSTOMERS 
WHERE ID IN (SELECT ID
            FROM CUSTOMERS);

UPDATE CUSTOMERS
SET SALARY = SALARY * 0.25
WHERE AGE IN (SELECT AGE FROM CUSTOMERS_BKP
                WHERE AGE >= 27 );

DELETE FROM CUSTOMERS
WHERE AGE IN (SELECT AGE FROM CUSTOMERS_BKP
                WHERE AGE > 27 );