SELECT cloumn1, cloumn2 FROM table1
WHERE CONDITON
UNION
SELECT cloumn1, cloumn2 FROM table2
WHERE CONDITON

SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
UNION
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
RIGHT JOIN ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- The UNION ALL Clause:
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
UNION ALL
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
RIGHT JOIN ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- INTERSECT Clause
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
INTERSECT
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
RIGHT JOIN ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- EXCEPT Clause
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID
EXCEPT
SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS
RIGHT JOIN ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;